baseURL = "https://maxturgeon.ca/"
languageCode = "en-ca"
title = "Max Turgeon"

theme = "researcher"

enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Max Turgeon"
  description = "Dimension Reduction at UManitoba"
  favicon = "icon.png"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Max Turgeon"
    url = "https://maxturgeon.ca"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Verdana"
    pageWidth = "1000px"
    avatarSize = "250px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 2
  [[menu.main]]
    name = "Software"
    url = "/software"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/mturgeon_cv.pdf"
    weight = 4
  [[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 5
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 7

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
